varincenti_app/apps/principal/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('varincenti_app.apps.principal.views',
	url(r'^$', 'home', name = 'home'),
	url(r'^Marcas/$', 'mark', name = 'mark'),
	url(r'^Contactenos/$', 'contact', name = 'contact'),
	url(r'^404/$', 'page_404', name = 'page_404'),
)

varincenti_app/apps/users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('varincenti_app.apps.users.views',
	url(r'^Login/$', 'authenticate_user', name = 'login'),
	url(r'^Logout/$', 'logout_user', name = 'logout'),
	url(r'^Registrarme/$', 'register_user', name = 'register'),
	url(r'^Find-user/$', 'find_player', name = 'find_player'),
)

varincenti_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('varincenti_app.apps.users.urls')),
	# url(r'^', include('varincenti_app.apps.principal.urls')),
	url('', include('social.apps.django_app.urls', namespace='social')),
	# url(r'^Marcas/ExtremeEntretairment/', include('varincenti_app.apps.extreme.urls')),
	url(r'^', include('varincenti_app.apps.extreme.urls')),
]

varincenti_app/apps/principal/models.py
from django.db import models

class Contact(models.Model):
	name_complete = models.CharField(max_length = 50)
	email = models.EmailField()
	subject = models.CharField(max_length = 100)
	message = models.CharField(max_length = 500)
	def __str__(self):
		return self.asunto

class State(models.Model):
	name = models.CharField(max_length = 30)
	class_tag = models.CharField(max_length = 30)
	def __str__(self):
		return self.name

varincenti_app/apps/users/models.py
from varincenti_app.apps.principal.models import State
from django.contrib.auth.models import User
from datetime import datetime
from django.db import models

class ProfileUser(models.Model):
	user = models.OneToOneField(User, primary_key = True)
	photo = models.ImageField(upload_to = 'image/users/', default = 'image/users/none.png', blank = True)
	photo_2 = models.TextField(blank = True, null = True)
	number_telephone = models.CharField(max_length = 10, blank = True, null = True)
	number_cellphone = models.CharField(max_length = 10)
	state = models.ForeignKey(State, blank = True, null = True, default = 8)
	def __str__(self):
		return str(self.user)

varincenti_app/apps/principal/forms.py
from django.forms import *
from django import forms
from .models import *

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'
		widgets = {
			'name_complete': TextInput(attrs = {'id': 'left-label', 'placeholder': 'Ingrese su nombre completo'}),
			'email': EmailInput(attrs = {'id': 'left-label', 'placeholder': 'Ingrese su correo electronico'}),
			'subject': TextInput(attrs = {'id': 'left-label', 'placeholder': 'Ingrese un asunto'}),
			'message': Textarea(attrs = {'id': 'left-label', 'placeholder': 'Ingrese Mensaje', 'cols': 30, 'rows': 5})
		}
		labels = {
			'name_complete': 'Nombre completo',
			'email': 'Correo electronico',
			'subject': 'Asunto',
			'message': 'Mensaje'
		}
		error_messages = {
			'name_complete': {
				'required': 'Por favor ingrese su nombre completo'
			},
			'email': {
				'required': 'Por favor ingrese su correo electronico'
			},
			'subject': {
				'required': 'Por favor ingrese un asunto'
			},
			'message': {
				'required': 'Por favor ingrese su mensaje'
			},
		}

varincenti_app/apps/users/forms.py
# -*- encoding: utf-8 -*-
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.conf import settings
from django.forms import *
from django import forms
from .models import *

class LoginForm(forms.Form):
	username = forms.CharField(label = 'Usuario', widget = forms.TextInput(attrs = {'class': 'form', 'placeholder': 'Ingresa tu usuario', 'autocomplete': 'off'}))
	password = forms.CharField(widget = forms.PasswordInput(attrs = {'class': 'form', 'placeholder': 'Ingresa tu Contraseña', 'autocomplete': 'off'}), label = 'Contraseña')

class RegisterForm(forms.Form):
	first_name = forms.CharField(label = 'Nombres', widget = forms.TextInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Ingrese su nombre'}))
	last_name = forms.CharField(label = 'Apellidos', widget = forms.TextInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Ingrese sus apellidos'}))
	email = forms.EmailField(label = 'Correo Electrónico', widget = forms.TextInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Ingrese su correo electrónico', 'type': 'email'}))
	number_telephone = forms.CharField(required = False, max_length = 10, label = 'Número Telefónico', widget = forms.TextInput(attrs = {'class': 'form', 'required': False, 'max_length': '10', 'placeholder': 'Digite su número de contácto telefónico'}))
	number_cellphone = forms.CharField(max_length = 10, label = 'Número Celular', widget = forms.TextInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Digite su número de contácto celular'}))
	username = forms.CharField(label = 'Usuario', widget = forms.TextInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Ingrese un usuario'}))
	password = forms.CharField(label = 'Contraseña', widget = forms.PasswordInput(attrs = {'class': 'form', 'required': True, 'placeholder': 'Ingrese su contraseña'}))
	birthdate = forms.CharField(label = 'Fecha de Nacimiento', widget = forms.TextInput(attrs = {'class' : 'form'}))
	photo = forms.ImageField(label = 'Foto', required = False)

	def clean_username(self):
		username = self.cleaned_data.get('username')
		if User.objects.filter(username = username).exists():
			raise forms.ValidationError('El usuario ya se encuentra en uso.')
		return username

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email = email).exists():
			raise forms.ValidationError('El email ya se ecuentra en uso.')
		return email

	def clean_number_telephone(self):
		number_telephone = self.cleaned_data.get('number_telephone')
		if number_telephone:
			if ProfileUser.objects.filter(number_telephone = number_telephone).exists():
				raise forms.ValidationError('El número ya se ecuentra en uso.')
		return number_telephone

	def clean_number_cellphone(self):
		number_cellphone = self.cleaned_data.get('number_cellphone')
		if ProfileUser.objects.filter(number_cellphone = number_cellphone).exists():
			raise forms.ValidationError('El número ya se ecuentra en uso.')
		return number_cellphone

	def save(self):
		first_name = self.cleaned_data.get('first_name')
		last_name = self.cleaned_data.get('last_name')
		email = self.cleaned_data.get('email')
		birthdate = self.cleaned_data.get('birthdate')
		number_telephone = self.cleaned_data.get('number_telephone')
		number_cellphone = self.cleaned_data.get('number_cellphone')
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		photo = self.cleaned_data.get('photo')
		user = User.objects.create_user(username, email, password)
		user.first_name = first_name
		user.last_name = last_name
		user.save()
		profile = ProfileUser(user = user, photo = photo, number_telephone = number_telephone, number_cellphone = number_cellphone, birthdate = birthdate)
		profile.save()

varincenti_app/apps/principal/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.forms import ModelForm
from .backends import *
from .forms import *

"""
@premissions_check
def home(request, *args):
	return render(request, 'varincenti/home.html', *args)
"""

def home(request, *args):
	title = 'Bienvenido'
	return render(request, 'varincenti/home.html', {'title': title})

def mark(request):
	title = 'Nuestras Marcas'
	return render(request, 'varincenti/mark.html', {'title': title})

def contact(request):
	title = 'Contactenos'
	if request.method == 'POST':
		form = ContactForm(request.POST)
		form.user = request.user
		if form.is_valid():
			if form.save():
				messages.add_message(request, 25, 'Gracias por contactarse con nosotros')
				return HttpResponseRedirect('/Contactenos')
			else:
				messages.add_message(request, 40, '<strong>Error!</strong> Ha ocurrido un error')
	else:
		form = ContactForm()
	return render(request, 'varincenti/contact.html', {'form': form, 'title': title})

def page_404(request):
	title = 'No encontrado'
	return render(request, 'varincenti/error/404.html', {'title': title, 'template': ' ', 'body': 'blue-light'})

varincenti_app/apps/users/views.py
# -*- encoding: utf-8 -*-
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from varincenti_app.apps.principal.backends import *
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.contrib import messages
from .models import *
from .forms import *
import json

@check_auth
def authenticate_user(request):
	title = 'Acceso'
	form = LoginForm()
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username = username, password = password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('home_extreme'))
			else:
				messages.add_message(request, 40, 'Usuario inactivo')
		else:
			messages.add_message(request, 30, 'Usuario no existente')
	return render(request, 'users/login.html', {'form': form, 'title': title, 'template': ' ', 'body': 'back'})

def logout_user(request):
	logout(request)
	messages.add_message(request, 25, 'Exito al cerrar sesión')
	return HttpResponseRedirect(reverse('login'))

@csrf_exempt
@check_auth
def register_user(request):
	title = 'Registro'
	if request.method == 'POST':
		form = RegisterForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			form.save()
			messages.add_message(request, 25, 'Te has Registrado')
			return HttpResponseRedirect(reverse('register'))
		else:
			messages.add_message(request, 30, 'Ha ocurrido un error')
	else:
		form = RegisterForm()
	return render(request, 'users/register.html', {'form': form, 'title': title, 'template': ' ', 'body': 'back'})

def find_player(request):
	if request.is_ajax:
		word = request.GET.get('term','')
		users = User.objects.filter(username__icontains = word)
		results = []
		for user in users:
			response = {}
			response['label'] = user.username+' - '+user.first_name+' '+user.last_name
			response['value'] = user.username
			results.append(response)
		data_json = json.dumps(results)
	else:
		data_json = 'fail'
	mimetype = "application/json"
	return HttpResponse(data_json, mimetype)

varincenti_app/apps/principal/templates/users/login.html
{% extends 'layout/varincenti.html' %}

{% block content_2 %}

<div class="container-init">
	<div class="large-4 large-offset-4 columns">
		<div class="row">
			{% for message in messages %}
				<div class="alert-box {{ message.tags }}">{{ message }}</div>
			{% endfor %}
		</div>
		<div class="box dark txt-center">
			<h4>Ingresar</h4>
		</div>
		<div class="card-login">
			<form action="{% url 'login' %}" class="form-access" method="post">
				{% csrf_token %}
				<div class="row">
				{% for forms in form %}
					<div class="small-12">
						<label class="text-right text-red-dark">
							{{ forms.errors.as_text }}
						</label>
						<div class="row text-center">
							<div class="medium-12 columns">
								{{ forms }}
							</div>
						</div>
					</div>
				{% endfor %}
				</div>
				<div class="text-center">
					<div class="row">
						<input type="submit" value="Ingresar" id="access" class="button success radius" />
					</div>
				</div>
				<br>
				<div class="row text-center">
					<div class="large-6 columns">
						<a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
							<div class="social fb">
								<i class="fi-social-facebook"></i> Ingresar con Facebook
							</div>
						</a>
					</div>
					<div class="large-6 columns">
						<a href="#">
							<div class="social tw">
								<i class="fi-social-twitter"></i> Ingresar con Twitter
							</div>
						</a>
					</div>
				</div>
			</form>
		</div>
		<div class="box dark txt-center">
			<p>¿No tienes cuenta? <a href="{% url 'register' %}">Registrate</a></p>
		</div>
		<div class="login-footer text-center">
			<p>&copy; 2015 Derechos Reservados. <a href="#">Varincenti</a> &reg;</p>
		</div>
	</div>
</div>

{% endblock content_2 %}

varincenti_app/apps/principal/templates/users/register.html
{% extends 'layout/varincenti.html' %}

{% load staticfiles %}

{% block content_head %}
	<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
	<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock content_head %}

{% block content_2 %}

<div class="container-init">
	<div class="large-8 large-offset-2 columns">
		<div class="row">
			{% for message in messages %}
				<div class="alert-box {{ message.tags }}">{{ message }}</div>
			{% endfor %}
		</div>
		<div class="box dark text-center">
			<h4>Registrate</h4>
		</div>
		<div class="card-login">
			<form action="{% url 'register' %}" method="post" class="form-access" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="row">
					{% for forms in form %}
						<div class="small-12 large-6 columns">
							<div class="row">
								<div class="large-12 columns">
									<label>
										{{ forms.label }}
									</label>
								</div>
								<div class="large-12 columns">
									{{ forms }}
								</div>
								<p class="text-right text-red-dark">
									{{ forms.errors.as_text }}
								</p>
							</div>
						</div>
					{% endfor %}
				</div>
				<div class="row">
					<div class="text-center">
						<input type="submit" value="Registrarme" id="access" class="button success radius" />
					</div>
				</div>
			</form>
			<br>
			<div class="row text-center">
				<div class="large-6 columns">
					<a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
						<div class="social fb">
							<i class="fi-social-facebook"></i> Registrarme con Facebook
						</div>
					</a>
				</div>
				<div class="large-6 columns">
					<a href="#">
						<div class="social tw">
							<i class="fi-social-twitter"></i> Registrarme con Twitter
						</div>
					</a>
				</div>
			</div>
		</div>
		<div class="box dark txt-center">
			<div class="row text-center">
				<p>¿Ya tienes una cuenta? <a href="{% url 'login' %}">Ingresa</a></p>
			</div>
		</div>
		<div class="login-footer text-center">
			<p>&copy; 2015 Derechos Reservados. <a href="#">Varincenti</a> &reg;</p>
		</div>
	</div>
</div>

{% endblock content_2 %}

{% block content_script %}
	$('#id_birthdate').datepicker({'format': 'yyyy-mm-dd', 'autoclose': true});
	$('#id_birthdate').datepicker('setDate', new Date());
{% endblock content_script %}