varincenti_app/apps/extreme/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('varincenti_app.apps.extreme.views',
	url(r'^invite/$', 'invite', name = 'invite'),
	url(r'^$', 'home_extreme', name = 'home_extreme'),
	url(r'^New-extreme/$', 'new_extreme', name = 'new_extreme'),
	url(r'^Edit-extreme/(?P<product_id>\d+)/$', 'edit_extreme', name = 'edit_extreme'),
	url(r'^New-camp/$', 'new_camp', name = 'new_camp'),
	url(r'^search-camp/', 'search_camp', name = 'search_camp'),
	url(r'^Productos/', 'product_extreme', name = 'product_extreme'),
	url(r'^Reservas/$', 'reservations', name = 'reservations'),
	url(r'^Reservas/(?P<extreme_id>\d+)/$', 'make_reservation', name = 'make_reservation'),
	url(r'^Reservas/(?P<reservation_id>\d+)/Agregar-jugadores/$', 'make_reservation_player', name = 'make_reservation_player'),
	url(r'^Reservas/(?P<reservation_player_id>\d+)/Eliminar-jugadores/$', 'delete_reservation_player', name = 'delete_reservation_player'),
	url(r'^Reservas/No-(?P<reservation_id>\d+)/Detalle/$', 'detail_reservation', name = 'detail_reservation'),
	url(r'^Reservas/No-(?P<reservation_id>\d+)/Eliminar/$', 'delete_reservation', name = 'delete_reservation'),
	url(r'^Reservas/No-(?P<reservation_id>\d+)/Cancelar_reserva/$', 'cancel_reservation', name = 'cancel_reservation'),
)

varincenti_app/apps/principal/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('varincenti_app.apps.principal.views',
	url(r'^$', 'home', name = 'home'),
	url(r'^Marcas/$', 'mark', name = 'mark'),
	url(r'^Contactenos/$', 'contact', name = 'contact'),
	url(r'^404/$', 'page_404', name = 'page_404'),
)

varincenti_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('varincenti_app.apps.users.urls')),
	# url(r'^', include('varincenti_app.apps.principal.urls')),
	url('', include('social.apps.django_app.urls', namespace='social')),
	# url(r'^Marcas/ExtremeEntretairment/', include('varincenti_app.apps.extreme.urls')),
	url(r'^', include('varincenti_app.apps.extreme.urls')),
]

varincenti_app/apps/extreme/models.py
from varincenti_app.apps.users.models import ProfileUser
from varincenti_app.apps.principal.models import State
from django.contrib.auth.models import User
from datetime import datetime
from django.db import models

class Product_extreme(models.Model):
	name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 100)
	tag = models.CharField(max_length = 250)
	conditions = models.CharField(max_length = 3000)
	photo = models.ImageField(upload_to = 'image/extreme/product/')
	state = models.ForeignKey(State, blank = False, null = True, default = 9)
	def __str__(self):
		return self.name

class Place_camp(models.Model):
	name = models.CharField(max_length = 100)
	direction = models.CharField(max_length = 100)
	description = models.CharField(max_length = 200, blank = True)
	ubication = models.CharField(max_length = 500, blank = True)
	photo = models.ImageField(upload_to = 'image/extreme/camp/', blank = True)
	def __str__(self):
		return self.name+' - '+self.direction

class Camp_product(models.Model):
	product_extreme = models.ForeignKey(Product_extreme, blank = False, null = True)
	place_camp = models.ForeignKey(Place_camp, blank = False, null = True)
	def __str__(self):
		return str(self.place_camp)

class Reservation(models.Model):
	user = models.ForeignKey(User, blank = False, null = True)
	date = models.DateTimeField(auto_now = False, default = datetime.now)
	date_reservation = models.DateField(default = datetime.now)
	hour_reservation = models.TimeField(blank = True, default = datetime.now)
	camp_product = models.ForeignKey(Camp_product, blank = False, null = True)
	state = models.ForeignKey(State, blank = False, null = True, default = 1)
	def __str__(self):
		return str(self.pk)

class Reservation_player(models.Model):
	reservation = models.ForeignKey(Reservation, blank = False, null = True)
	player_user = models.ForeignKey(User, blank = False, null = True)
	def __str__(self):
		return str(self.reservation)

varincenti_app/apps/extreme/forms.py
# -*- encoding: utf-8 -*-
from varincenti_app.apps.users.models import ProfileUser
from django.contrib.auth.models import User
from datetime import timedelta, time
from django.forms import *
from django import forms
from .models import *

class CustomDateInput(widgets.TextInput):
	input_type = 'date'

class ReservationForm(forms.ModelForm):
	class Meta:
		model = Reservation
		fields = '__all__'
		widgets = {
			'date_reservation': TextInput,
			'hour_reservation': TimeInput,
		}
		labels = {
			'camp_product': 'Campo',
			'date_reservation': 'Fecha de la Reserva',
			'hour_reservation': 'Hora de la Reserva',
		}
		exclude = ('state', 'date', 'user')

	def __init__(self, *args, **kwargs):
		product_extreme = kwargs.pop('product_extreme', None)
		super(ReservationForm, self).__init__(*args, **kwargs)
		if product_extreme:
			self.fields['camp_product'] = forms.ModelChoiceField(label = 'Campo', queryset = Camp_product.objects.filter(product_extreme = product_extreme), empty_label = 'Seleccione un Campo')

	def save(self):
		user = User.objects.get(username = self.instance)
		date_reservation = self.cleaned_data.get('date_reservation')
		hour_reservation = self.cleaned_data.get('hour_reservation')
		camp_product = self.cleaned_data.get('camp_product')
		reservation = Reservation(user = user, date_reservation = date_reservation, hour_reservation = hour_reservation, camp_product = camp_product)
		reservation.save()
		reservation_player = Reservation_player(reservation = reservation, player_user = user)
		reservation_player.save()
		return reservation

class ReservationPlayerForm(forms.ModelForm):
	class Meta:
		model = Reservation_player
		fields = '__all__'
		widgets = {
			'player_user': TextInput(attrs = {'required': True, 'placeholder': 'Escribe el nombre de usuario del jugador'}),
		}
		exclude = ('reservation',)

	def clean_player_user(self):
		reservation = Reservation.objects.get(pk = str(self.instance))
		player_user = self.cleaned_data.get('player_user')
		user = User.objects.get(username = player_user)
		if user.profileuser.state.id == 7:
			raise forms.ValidationError('El usuario '+user.username+' se encuentra en estado '+str(user.profileuser.state))
		else:
			if Reservation_player.objects.filter(reservation = reservation, player_user = user).exists():
				raise forms.ValidationError('El usuario '+user.username+' ya se encuentra agregado.')
		return player_user

class ProductForm(forms.Form):
	name = forms.CharField(label = 'Nombre del ExtremeEntertainment', widget = forms.TextInput(attrs = {'required': True, 'placeholder': 'Escribe el nombre del ExtremeEntertainment'}))
	tag = forms.CharField(label = 'Tag', widget = forms.TextInput(attrs = {'readonly': True}))
	photo = forms.ImageField(label = 'Foto', required = False)
	description = forms.CharField(label = 'Descripcion', widget = forms.TextInput(attrs = {'required': True, 'placeholder': 'Escribe una descripcion'}))
	conditions = forms.CharField(label = 'Condiciones', widget = forms.Textarea(attrs = {'required': True}))
	camp = forms.ModelMultipleChoiceField(label = 'Campo(s)', queryset = Place_camp.objects.all())

	def save(self):
		name = self.cleaned_data.get('name')
		tag = self.cleaned_data.get('tag')
		photo = self.cleaned_data.get('photo')
		description = self.cleaned_data.get('description')
		conditions = self.cleaned_data.get('conditions')
		camp = self.cleaned_data.get('camp')
		product = Product_extreme(name = name, tag = tag, photo = photo, description = description, conditions = conditions)
		product.save()
		for camps in camp:
			place_camp = Place_camp.objects.get(pk = camps.pk)
			camp_product = Camp_product(product_extreme = product, place_camp = place_camp)
			camp_product.save()
		return product

class CampForm(forms.ModelForm):
	class Meta:
		model = Place_camp
		fields = '__all__'
		widgets = {
			'name': TextInput(attrs = {'required': True, 'placeholder': 'Ingrese el nombre del campo'}),
			'direction': TextInput(attrs = {'required': True, 'placeholder': 'Ingrese la direccion del campo'}),
			'description': TextInput(attrs = {'placeholder': 'Ingrese una descripcion corta del campo'}),
			'ubication': TextInput(attrs = {'required': True, 'placeholder': 'Ingrese la ubicacion del campo'}),
		}
		labels = {
			'name': 'Nombre del Campo',
			'direction': 'Direccion del Campo',
			'description': 'Descripcion',
			'ubication': 'Ubication (Google Maps)',
			'photo': 'Foto'
		}

varincenti_app/apps/extreme/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from varincenti_app.apps.principal.backends import *
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.contrib import messages
from django.shortcuts import render
from django.conf import settings
from requests import request
from .models import *
from .forms import *
import json

def home_extreme(request):
	title = 'Extreme Entretairment'
	body = 'extreme'
	return render(request, 'extreme/home.html', {'title': title})

def product_extreme(request):
	if request.user.is_superuser:
		product = Product_extreme.objects.all()
	else:
		product = Product_extreme.objects.filter(state = 9)
	title = 'Nuestros productos'
	return render(request, 'extreme/product.html', {'title': title, 'products': product, 'row': 0})

@login_required(login_url = '/Login')
def invite(request):
	friends = get_friends(request.user)
	return render(request, 'extreme/invite.html', {'friends': friends, 'SOCIAL_AUTH_FACEBOOK_KEY': settings.SOCIAL_AUTH_FACEBOOK_KEY})

def get_friends(user):
	facebook = user.social_auth.get(provider='facebook')
	url = 'https://graph.facebook.com/v2.5/me/taggable_friends?'.format(facebook.uid)
	friends = request('GET', url, params={'access_token': facebook.extra_data['access_token']}).json()
	print(friends)
	return friends['data']

@login_required(login_url = '/Login')
def make_reservation(request, extreme_id):
	title = 'Reservaciones'
	product = Product_extreme.objects.get(pk = extreme_id)
	if request.method == 'POST':
		if request.user.profileuser.state.id != 7:
			form = ReservationForm(request.POST, instance = request.user, product_extreme = product.id)
			if form.is_valid():
				save_form = form.save()
				messages.add_message(request, 25, 'Reserva Exitosa, continua ingresando los jugadores.')
				return HttpResponseRedirect(reverse('make_reservation_player', kwargs = {'reservation_id': save_form.id}))
		else:
			form = ReservationForm(product_extreme = product.id, instance = request.user)
			messages.add_message(request, 40, 'No puedes realizar la reserva, tienes multa.')
			return render(request, 'extreme/reservation.html', {'title': title, 'product': product, 'form': form})
	else:
		form = ReservationForm(product_extreme = product.id, instance = request.user)
	return render(request, 'extreme/reservation.html', {'title': title, 'product': product, 'form': form})

@login_required(login_url = '/Login')
def make_reservation_player(request, reservation_id):
	title = 'Agrega a tu equipo'
	players = Reservation_player.objects.filter(reservation = reservation_id)
	reservation_data = Reservation.objects.get(pk = reservation_id)
	reservation = Reservation_player(reservation = reservation_data)
	if request.method == 'POST':
		user = User.objects.get(username = request.POST['player_user'])
		request.POST = request.POST.copy()
		request.POST['player_user'] = user.pk
		form = ReservationPlayerForm(request.POST, instance = reservation)
		if form.is_valid():
			form.save()
			messages.add_message(request, 25, 'Usuario agregado exitosamente.')
			return HttpResponseRedirect(reverse('make_reservation_player', kwargs = {'reservation_id': reservation_id}))
		else:
			request.POST['player_user'] = user.username
			messages.add_message(request, 40, 'Ha ocurrido un error.')
	else:
		form = ReservationPlayerForm(instance = reservation)
	return render(request, 'extreme/reservation_player.html', {'title': title, 'players': players, 'form': form, 'reservation': reservation_data})

@login_required(login_url = '/Login')
def delete_reservation_player(request, reservation_player_id):
	reservation_player = Reservation_player.objects.get(pk = reservation_player_id)
	reservation_id = reservation_player.reservation
	user = reservation_player.reservation.user
	if user == request.user or request.user.is_superuser:
		reservation_player.delete()
		messages.add_message(request, 25, 'Jugador eliminado exitosamente.')
		return HttpResponseRedirect(reverse('make_reservation_player', kwargs = {'reservation_id': reservation_id}))
	else:
		return HttpResponseRedirect('/404')

@login_required(login_url = '/Login')
def reservations(request):
	title = 'Mis Reservas'
	if request.user.is_superuser:
		reservations = Reservation.objects.all().order_by('state')
	else:
		reservations = Reservation.objects.filter(user = request.user).order_by('state')
	return render(request, 'extreme/my-reservation.html', {'title': title, 'reservations': reservations})

@login_required(login_url = '/Login')
def detail_reservation(request, reservation_id):
	title = 'Reserva No.'+reservation_id
	try:
		if request.user.is_superuser:
			reservation = Reservation.objects.get(pk = reservation_id)
		else:
			reservation = Reservation.objects.get(pk = reservation_id, user = request.user)
	except Reservation.DoesNotExist:
		return HttpResponseRedirect('/404')
	return render(request, 'extreme/detail-reservation.html', {'title': title, 'reservation': reservation})

@login_required(login_url = '/Login')
def cancel_reservation(request, reservation_id):
	reservation = Reservation.objects.get(pk = reservation_id)
	if reservation.user == request.user or request.user.is_superuser:
		state_cancel = State.objects.get(pk = 4)
		reservation.state = state_cancel
		date_now = datetime.now().strftime('%Y-%m-%d')
		date_reser = reservation.date_reservation - timedelta(days = 3)
		print(date_now)
		if str(date_now) >= str(date_reser):
			messages.add_message(request, 40, 'Ya no puedes cancelar la reserva.')
		else:
			reservation.save(update_fields = ['state'])
			messages.add_message(request, 25, 'Exito al cancelar la reserva.')
	else:
		return HttpResponseRedirect('/404')
	return HttpResponseRedirect(reverse('reservations'))

@csrf_exempt
def search_camp(request):
	response = {}
	if request.method == 'POST':
		camp_product = Camp_product.objects.get(pk = request.POST.get('id'))
		response['ubication'] = str(camp_product.place_camp.ubication)
		response['photo'] = str(camp_product.place_camp.photo)
		response['name'] = str(camp_product.place_camp.name)
	else:
		response['error'] = 'Ha ocurrido un error'
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@premissions_check
def delete_reservation(request, reservation_id):
	reservation = Reservation.objects.get(pk = reservation_id)
	reservation.delete()
	messages.add_message(request, 25, 'Reserva eliminada exitosamente.')
	return HttpResponseRedirect(reverse('reservations'))

@premissions_check
def new_extreme(request):
	title = 'Agregar nuevo extreme'
	if request.method == 'POST':
		response = {}
		form = ProductForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			extreme = form.save()
			response['name'] = extreme.name
			response['description'] = extreme.description
			response['pk'] = extreme.pk
			response['state'] = extreme.state.name
			response['class_tag'] = extreme.state.class_tag
			response['photo'] = str(extreme.photo)
		else:
			response['response'] = "Error al guardar"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = ProductForm()
	return render(request, 'extreme/new-extreme.html', {'title': title, 'form': form})

@premissions_check
def edit_extreme(request, product_id):
	pass

@csrf_exempt
def new_camp(request):
	title = 'Agregar Campo'
	if request.method == 'POST':
		response = {}
		form = CampForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			form.save()
			response['response'] = "Exito al guardar"
		else:
			response['response'] = "Error al guardar"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = CampForm()
		return render(request, 'extreme/new-camp.html', {'title': title, 'form': form})

varincenti_app/apps/principal/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.forms import ModelForm
from .backends import *
from .forms import *

"""
@premissions_check
def home(request, *args):
	return render(request, 'varincenti/home.html', *args)
"""

def home(request, *args):
	title = 'Bienvenido'
	return render(request, 'varincenti/home.html', {'title': title})

def mark(request):
	title = 'Nuestras Marcas'
	return render(request, 'varincenti/mark.html', {'title': title})

def contact(request):
	title = 'Contactenos'
	if request.method == 'POST':
		form = ContactForm(request.POST)
		form.user = request.user
		if form.is_valid():
			if form.save():
				messages.add_message(request, 25, 'Gracias por contactarse con nosotros')
				return HttpResponseRedirect('/Contactenos')
			else:
				messages.add_message(request, 40, '<strong>Error!</strong> Ha ocurrido un error')
	else:
		form = ContactForm()
	return render(request, 'varincenti/contact.html', {'form': form, 'title': title})

def page_404(request):
	title = 'No encontrado'
	return render(request, 'varincenti/error/404.html', {'title': title, 'template': ' ', 'body': 'blue-light'})

varincenti_app/apps/principal/templates/extreme/new-camp.html
{% load staticfiles %}

<div class="modal-title">
	<h3 id="modalTitle">{{ title }}</h3>
</div>
<div class="content-modal">
	<form id="form-camp" action="{% url 'new_camp' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="large-6 columns">
			<label> {{ form.name.label }}
			{{ form.name }}
			</label>
		</div>
		<div class="large-6 columns">
			<label> {{ form.direction.label }}
			{{ form.direction }}
			</label>
		</div>
		<div class="large-12 columns">
			<label> {{ form.description.label }}
			{{ form.description }}
			</label>
		</div>
		<div class="large-6 columns">
			<label> {{ form.ubication.label }}
			{{ form.ubication }}
			</label>
		</div>
		<div class="large-6 columns">
			<label> {{ form.photo.label }}
			{{ form.photo }}
			</label>
		</div>
		<div class="large-12 columns text-center">
			<div id="ubication-map"></div>
		</div>
		<div class="large-12 columns">
			<div class="text-center">
				<input type="submit" value="Guardar" class="button success radius" />
			</div>
		</div>
	</form>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<script>
	$("#id_ubication").keyup(function(){
		$('#ubication-map').html('<iframe src="'+$(this).val()+'" width="600" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>');
	});
	$("form#form-camp").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				show_content();
				$('#new-camp').foundation('reveal', 'close');
				$('#new-camp').empty();
			}
		});
	});
</script>

varincenti_app/apps/principal/templates/extreme/new-extreme.html
{% load staticfiles %}

<div class="row">
	<div class="close">
		<a href="#" class="close-content">
			<h4>
				<i class="fi-x text-red"></i>
			</h4>
		</a>
	</div>
	<h3>{{ title }}</h3>
	<form action="{% url 'new_extreme' %}" id="form-extreme" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="large-6 columns">
			<label> {{ form.name.label }}
				{{ form.name }}
			</label>
		</div>
		<div class="large-6 columns">
			<label> {{ form.tag.label }}
				{{ form.tag }}
			</label>
		</div>
		<div class="large-12 columns">
			<label> {{ form.description.label }}
				{{ form.description }}
			</label>
		</div>
		<div class="large-12 columns">
			<label> {{ form.conditions.label }}
				{{ form.conditions }}
			</label>
		</div>
		<div class="large-6 columns">
			<label> {{ form.camp.label }}
				{{ form.camp }}
			</label>
			<a href="{% url 'new_camp' %}" class="add_camp"><i class="fi-plus"></i> Agregar Campo</a>
		</div>
		<div class="large-6 columns">
			<label> {{ form.photo.label }}
				{{ form.photo }}
			</label>
			<img src="{% static 'image/users/none.png' %}" alt="" id="image" class="image-product">
		</div>
		<div class="large-12 columns">
			<div class="text-center">
				<input type="submit" value="Guardar" class="button success radius" />
			</div>
		</div>
	</form>
</div>
<div id="new-camp" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"></div>
<script>
	$("#id_conditions").jqte();
	$("#id_name").keyup(function(){
		$('#id_tag').val($('#id_name').val().replace(/ /g, "-").toLowerCase());
	});
	$(".close-content").click(function(e){
		e.preventDefault();
		$('#content-new-extreme').removeClass('back-white');
		$('#content-new-extreme').empty();
	});
	$("#id_photo").change(function() {
		readURL(this);
	});
	function readURL(input){
		if(input.files && input.files[0]){
			var reader = new FileReader();
			reader.onload = function (e){
				$('#image').attr('src', e.target.result);
			}
			reader.readAsDataURL(input.files[0]);
		}
	}
	$(".add_camp").click(function(){
		$('#new-camp').foundation('reveal', 'open', {
			url: $(this).attr('href')
		});
		return false;
	});
	$("form#form-extreme").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				$('#content-list-product').append(
					"<li>"+
						"<div class='profile-card text-center'>"+
							"<div class='text-center'>"+
								"<div class='"+data.class_tag+"'>"+
									"<p>"
										+data.state+
										"<span class='fi-widget' style='float: right; padding-right: 10px;'></span>"+
									"</p>"+
								"</div>"+
							"</div>"+
							"<img src='/static/"+data.photo+"' class='image-product'>"+
								"<div class='profile-info'>"+
									"<h4 class='subheader'>"+data.name+"</h4>"+
									"<p>"+data.description+"</p>"+
									"<a href='"+data.pk+"' class='button success radius'>Reservar Campo</a>"+
							"</div>"+
						"</div>"+
					"</li>"
				);
				$('#content-new-extreme').removeClass('back-white');
				$('#content-new-extreme').empty();
			}
		});
	});
</script>

varincenti_app/apps/principal/templates/extreme/reservation.html
{% extends 'layout/varincenti.html' %}

{% load staticfiles %}

{% block content_head %}
	<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
	<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
	<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock content_head %}

{% block content_nav %}
	{% include 'elements/nav_extreme.html' %}
{% endblock content_nav %}

{% block content %}
	<div class="head-title index">
		<div class="row text-center">
			<h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </h1>
			<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc finibus vitae urna sed pretium.</p>
		</div>
	</div>
	<div class="back-white">
		<div class="row">
			{% for message in messages %}
				<div class="text-left alert-box {{ message.tags }}">{{ message }}</div>
			{% endfor %}
			<div class="small-12 large-4 columns">
				<div class="text-center">
					<img src="{% static product.photo %}" class="img-square" style="width: 200px; height: 200px; margin-bottom: 10px;">
					<p>{{ product.description }}</p>
				</div>
			</div>
			<div class="small-12 large-8 columns">
				<h3>Hola {{ request.user.first_name }}, haz una reserva en {{ product.name }}</h3>
				<form action="{% url 'make_reservation' product.id %}" method="post">
					{% csrf_token %}
					{% for forms in form %}
						<label class="text-right text-red-dark">
							{{ forms.errors.as_text }}
						</label>
						<label>{{ forms.label }}</label>
						{{ forms }}
					{% endfor %}
					<div class="text-center">
						<input type="submit" value="Continuar" class="button success radius" />
					</div>
				</form>
			</div>
			<div class="small-12 large-6 columns">
				<div class="map-camp text-center"></div>
			</div>
			<div class="small-12 large-6 columns">
				<div class="photo-camp text-center"></div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block content_footer %}
	{% include 'elements/footer_extreme.html' %}
{% endblock content_footer %}

{% block content_script %}
	$('#id_hour_reservation').val('09:00');
	$('#id_hour_reservation').timepicker({
		minTime: '09:00', 
		maxTime: '17:00',
		timeFormat: 'H:i',
		default: '09:00',
		step: '60'
	});
	$('#id_date_reservation').datepicker({'format': 'yyyy-mm-dd', 'autoclose': true});
	$('#id_date_reservation').datepicker('setDate', new Date());
	$('#id_camp_product').change(function(){
		if($('#id_camp_product').val() != ''){
			$.ajax({
				url: '{% url 'search_camp' %}',
				type: 'POST',
				data: {id: $(this).val()},
				success: function(json){
					$('.map-camp').html('<iframe src="'+json.ubication+'" width="500" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>');
					$('.photo-camp').html('<img src="/static/'+json.photo+'" alt="'+json.name+'" width="400px" height="auto">');
					console.log(json.photo);
				},
				error: function(json){
					$('.map-camp').html('<h3>'+json.error+'</h3>')
				}
			});
		}else{
			alert('Seleccione un valor');
		}
	});
{% endblock content_script %}